### PR TITLE
More design tweaks

### PR DESCRIPTION
**Pull request by DominikTo**
More tweaks from @demkani:

* Sidebar improvements (scrolling & toggle).
* More space for code blocks on small screens/mobiles.
* "Line up" boxes no longer look odd with less text.
* Pretty support page.

### CODE REVIEW

**Comment by evert** [comment]
Is this ready for testing and merging?

**Comment by DominikTo** [comment]
Yep.

**Comment by evert** [comment]
Code looks fine.. gonna merge it for easy local testing.

**Comment by evert** [comment]
pretty =)

**Comment by evert** [comment]
Deployed

**Comment by DominikTo** [comment]
\o/ @demkani :-)

**Pull request merged**
